name: Example
on: [push, pull_request]
   
# jobs:
#   nsa-security-check:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Install Kubescape
#         run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
        
#       - name: Scan YAML files
#         run: kubescape scan framework nsa *.yaml
jobs:
  kubescape-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: kubescape/github-action@main
        with:
          threshold: "50"
          args: "--format junit --output results.xml"
          files: "*.yaml"
          framework: nsa
      - name: Archive kubescape scan results
        uses: actions/upload-artifact@v2
        with:
          name: kubescape-scan-report
          path: results.xml
      - name: Publish Unit Test Results
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: "*.xml" 
